# Generated by Django 4.2.7 on 2025-03-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQs', '0004_remove_question_test_question_level_question_subject_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together={('test', 'order')},
        ),
    ]
