# Generated by Django 4.2.7 on 2025-03-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_level_level_name'),
        ('MCQs', '0005_alter_testquestion_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('notes', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCQs.test')),
            ],
        ),
    ]
